# Generated by Django 4.0.3 on 2022-03-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Walls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Название')),
                ('wall', models.ImageField(upload_to='walls/%Y/%m/%d/', verbose_name='Обои')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Обои',
                'verbose_name_plural': 'Обои',
            },
        ),
    ]
