# Generated by Django 4.0.3 on 2022-08-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walls', '0002_category_walls_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='walls',
            name='cat',
        ),
        migrations.AddField(
            model_name='walls',
            name='cat',
            field=models.ManyToManyField(null=True, to='walls.category'),
        ),
        migrations.AlterField(
            model_name='walls',
            name='title',
            field=models.CharField(blank=True, max_length=55, verbose_name='Название'),
        ),
    ]
