# Generated by Django 4.0.3 on 2022-11-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walls', '0003_alter_category_options_remove_walls_cat_walls_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walls',
            name='cat',
            field=models.ManyToManyField(to='walls.category'),
        ),
    ]
